# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "CS 101: Merhaba, Dünya!"
email: your-email@domain.com
author: "CS 101: Merhaba, Dünya!"
copyright: Copyright © 2020
description: >
  CS 101: Merhaba, dünya! Türkiye'deki lise öğrencileri arasında programlama 
  eğitimini ve takip eden profesyonel, teknik, sosyal ve kişisel becerileri 
  teşvik etmek için dizayn edilmiş 8 haftalık online bir programdır. 
  CS 101 genel kanının aksine programlama eğitiminin kişilerin yatkın 
  olduğu alanlardan bağımsız olarak problem çözme, yaratıcı ve analitik düşünme 
  becerilerine katkısı olduğuna inanır, öğrencilerinin bu alanlardaki özgüvenlerini 
  artırmayı hedefler.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cs101-merhabadunya.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "" # the favicon for your site

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%d %b %Y"

header_pages:
  - about.html
  - resources.html
  - lectures.html
  - projects.html
collections:
  projects:
    output: true
    #rel_url: true
    permalink: /projeler/:slug #todo: find a better way
  lectures:
    output: true
# If you want more debug log, you can set true
# debug: false

# If you don't want transparent header, you can set false
header_transparent: false

# Google analytics
google_analytics: UA-179081985-1 #[Tracking ID]

# If you want to generate website sitemap, you can set true
# sitemap: false

# If you want to change site language, you can set lang option
# lang: "en"  # default lang is en
lang: "tr"
# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
# translate_langs:
#   - lang: en
#     text: English
#
#   - lang: fr
#     img: https://www.countryflags.io/fr/flat/64.png
#     text: Franch
#
#   - lang: zh-CN
#     img: https://www.countryflags.io/cn/flat/64.png
#     text: Chinese(Simple)
#
#   - lang: zh-TW
#     img: https://www.countryflags.io/tw/flat/64.png
#     text: Chinese(Traditional)
#
#   - lang: ja
#     img: https://www.countryflags.io/jp/flat/64.png
#     text: Japan
#
#   - lang: ko
#     img: https://www.countryflags.io/kr/flat/64.png
#     text: Korean
#
#   - lang: ru
#     img: https://www.countryflags.io/ru/flat/64.png
#     text: Russia

# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
#
# Custom color as below:
# theme_color: "#882250"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - index.html
#   - archives.html
#   - categories.html
#   - tags.html
#   - about.md

# Page default value
# defaults:
#   home:
#     heading: "Your awesome heading"
#     subheading: "Your awesome subheading"
#     banner: "Your image url"

# Pagination setting
# paginate: 5

# Disqus comments
# disqus:
#   shortname: "Your Disqus username"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM
theme: jekyll-theme-yat

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
